### ISSUE TITLE
The process crashed some time after starting successfully

### ISSUE THREAD

**Issue by abylikhsanov** [cyberbotics/webots#1524]
**Describe the Bug**
After trying to go through the tutorial for creating the controller [here](https://cyberbotics.com/doc/guide/tutorial-1-your-first-simulation-in-webots?tab-language=python) I get a warning:

```
WARNING: e_p: The process crashed some time after starting successfully.
WARNING: 'e_p' controller crashed.
```

**Steps to Reproduce**
Follow the tutorial for creating a new controller and use the same code in C++ or Python. The bug seems to happen when creating a `Robot` object.

**System**
 - Operating System: [Linux Ubuntu 18.04]
 - Graphics Card: [NVIDIA GeForce RTX 2070 8 GB.]

**Comment by DavidMansolino** [comment]
Can you share the code you are using (just to make 100% sure it is correct according to the tutorial) ?
You are using the 2020a-revision1 version of Webots right?

**Comment by abylikhsanov** [comment]
Here is the code:

```
#include <webots/Robot.hpp>

// Added a new include file
#include <webots/Motor.hpp>

#define TIME_STEP 64

// All the webots classes are defined in the "webots" namespace
using namespace webots;

int main(int argc, char **argv) {
 Robot *robot = new Robot();

 // get the motor devices
 Motor *leftMotor = robot->getMotor("left wheel motor");
 Motor *rightMotor = robot->getMotor("right wheel motor");
 // set the target position of the motors
 leftMotor->setPosition(10.0);
 rightMotor->setPosition(10.0);

 while (robot->step(TIME_STEP) != -1);

 delete robot;

 return 0;
```

I installed the binaries (via `apt`) and I do remember it was 2020 version but do not remember letter or revision (I will check tomorrow in the office) but should be the latest release if I installed the binaries.

**Comment by DavidMansolino** [comment]
I can indeed reproduce the crash (at least with the Python version of the controller).

**Comment by abylikhsanov** [comment]
Hi, yes the version is `R2020a rev 1`

**Comment by DavidMansolino** [comment]
I can indeed reproduce it with ``R2020a rev 1`` (but not with my development environment), I am currently installing a nightly build to see if this happens too.

**Comment by DavidMansolino** [comment]
I can confirm it is crashing with the nightly releases too.

**Comment by DavidMansolino** [comment]
The crash happens only with Python3.x (it is working fine with Python 2.7), and here is the stack on Mac:
```
Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [37599]

VM Regions Near 0x8:
--> 
    __TEXT                 000000010688b000-000000010688c000 [    4K] r-x/r-x SM=COW  /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.python.python             	0x0000000107124eac PyTuple_New + 252
1   org.python.python             	0x00000001071279aa PyType_Ready + 218
2   org.python.python             	0x000000010712796c PyType_Ready + 156
3   _controller.so                	0x0000000106fc925d SwigPyPacked_TypeOnce() + 77
4   _controller.so                	0x0000000106f80baf SwigPyPacked_type() + 47
5   _controller.so                	0x0000000106f7ec62 PyInit__controller + 34
6   org.python.python3            	0x00000001069ad123 _PyImport_LoadDynamicModuleWithSpec + 579
7   org.python.python3            	0x00000001069acb70 _imp_create_dynamic + 352
8   org.python.python3            	0x00000001068b764e _PyMethodDef_RawFastCallDict + 542
9   org.python.python3            	0x00000001068b7148 PyCFunction_Call + 200
10  org.python.python3            	0x0000000106988f65 _PyEval_EvalFrameDefault + 29365
11  org.python.python3            	0x000000010698d108 _PyEval_EvalCodeWithName + 2888
12  org.python.python3            	0x00000001068b6e54 _PyFunction_FastCallKeywords + 228
13  org.python.python3            	0x000000010698c40c call_function + 780
14  org.python.python3            	0x0000000106988b78 _PyEval_EvalFrameDefault + 28360
15  org.python.python3            	0x00000001068b737d function_code_fastcall + 237
16  org.python.python3            	0x000000010698c40c call_function + 780
17  org.python.python3            	0x0000000106988b5b _PyEval_EvalFrameDefault + 28331
18  org.python.python3            	0x00000001068b737d function_code_fastcall + 237
19  org.python.python3            	0x000000010698c40c call_function + 780
20  org.python.python3            	0x0000000106988c18 _PyEval_EvalFrameDefault + 28520
21  org.python.python3            	0x00000001068b737d function_code_fastcall + 237
22  org.python.python3            	0x000000010698c40c call_function + 780
23  org.python.python3            	0x0000000106988c18 _PyEval_EvalFrameDefault + 28520
24  org.python.python3            	0x00000001068b737d function_code_fastcall + 237
25  org.python.python3            	0x000000010698c40c call_function + 780
26  org.python.python3            	0x0000000106988c18 _PyEval_EvalFrameDefault + 28520
27  org.python.python3            	0x00000001068b737d function_code_fastcall + 237
28  org.python.python3            	0x00000001068b8c96 object_vacall + 614
29  org.python.python3            	0x00000001068b8d7d _PyObject_CallMethodIdObjArgs + 173
30  org.python.python3            	0x00000001069abab9 PyImport_ImportModuleLevelObject + 1657
31  org.python.python3            	0x0000000106987303 _PyEval_EvalFrameDefault + 22099
32  org.python.python3            	0x000000010698d108 _PyEval_EvalCodeWithName + 2888
33  org.python.python3            	0x0000000106981c10 PyEval_EvalCode + 48
34  org.python.python3            	0x000000010697f297 builtin_exec + 583
35  org.python.python3            	0x00000001068b764e _PyMethodDef_RawFastCallDict + 542
36  org.python.python3            	0x00000001068b7148 PyCFunction_Call + 200
37  org.python.python3            	0x0000000106988f65 _PyEval_EvalFrameDefault + 29365
38  org.python.python3            	0x000000010698d108 _PyEval_EvalCodeWithName + 2888
39  org.python.python3            	0x00000001068b6e54 _PyFunction_FastCallKeywords + 228
40  org.python.python3            	0x000000010698c40c call_function + 780
41  org.python.python3            	0x0000000106988b78 _PyEval_EvalFrameDefault + 28360
42  org.python.python3            	0x00000001068b737d function_code_fastcall + 237
43  org.python.python3            	0x000000010698c40c call_function + 780
44  org.python.python3            	0x0000000106988b5b _PyEval_EvalFrameDefault + 28331
45  org.python.python3            	0x00000001068b737d function_code_fastcall + 237
46  org.python.python3            	0x000000010698c40c call_function + 780
47  org.python.python3            	0x0000000106988c18 _PyEval_EvalFrameDefault + 28520
48  org.python.python3            	0x00000001068b737d function_code_fastcall + 237
49  org.python.python3            	0x000000010698c40c call_function + 780
50  org.python.python3            	0x0000000106988c18 _PyEval_EvalFrameDefault + 28520
51  org.python.python3            	0x00000001068b737d function_code_fastcall + 237
52  org.python.python3            	0x00000001068b8c96 object_vacall + 614
53  org.python.python3            	0x00000001068b8d7d _PyObject_CallMethodIdObjArgs + 173
54  org.python.python3            	0x00000001069abab9 PyImport_ImportModuleLevelObject + 1657
55  org.python.python3            	0x0000000106987303 _PyEval_EvalFrameDefault + 22099
56  org.python.python3            	0x000000010698d108 _PyEval_EvalCodeWithName + 2888
57  org.python.python3            	0x0000000106981c10 PyEval_EvalCode + 48
58  org.python.python3            	0x00000001069c4b9e PyRun_FileExFlags + 174
59  org.python.python3            	0x00000001069c413e PyRun_SimpleFileExFlags + 270
60  org.python.python3            	0x00000001069e68fe pymain_main + 6590
61  org.python.python3            	0x00000001069e72bf _Py_UnixMain + 111
62  libdyld.dylib                 	0x00007fff680c87fd start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000000  rcx: 0x00000001073ed070  rdx: 0x0000000000000001
  rdi: 0x0000000000000038  rsi: 0x00000000000000b0  rbp: 0x00007ffee93719a0  rsp: 0x00007ffee9371990
   r8: 0x00000000000fb30b   r9: 0xffffffff00000000  r10: 0x00007fff91ba68b0  r11: 0x0000000000007260
  r12: 0x0000000106ea6e30  r13: 0x0000000106f18198  r14: 0x00000001073ed090  r15: 0x0000000106f09e40
  rip: 0x0000000107124eac  rfl: 0x0000000000010286  cr2: 0x0000000000000008
  
Logical CPU:     8
Error Code:      0x00000004 (no mapping for user data write)
Trap Number:     14


Binary Images:
       0x10688b000 -        0x10688bff3 +org.python.python3 (3.7.3 - 3.7.3) <90518D96-45DE-39CA-A6F7-3A002B083985> /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python
       0x106894000 -        0x106a8ffff +org.python.python3 (3.7.3 - 3.7.3) <1F159C09-A47A-381B-B480-6863B43AF4B8> /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/Python3
       0x106f7e000 -        0x106fe2ff7 +_controller.so (0) <6DF0E2F1-91AA-3D31-81B6-F3E82F6BDF2F> /Applications/Webots.app/lib/controller/python37/_controller.so
       0x107009000 -        0x107065ffb +libController.dylib (0) <4D8777EF-7580-35EC-BD40-6449CA1CB68B> /Applications/Webots.app/lib/controller/libController.dylib
       0x107077000 -        0x10708effb +libCppController.dylib (0) <E716B789-93E9-3D4E-893B-315A3F74D4C7> /Applications/Webots.app/lib/controller/libCppController.dylib
       0x1070bd000 -        0x107297ff7 +org.python.python (3.7.6, [c] 2001-2019 Python Software Foundation. - 3.7.6) <D755D0C1-4FAA-358E-8F23-916770C7CD44> /Library/Frameworks/Python.framework/Versions/3.7/Python
       0x10ca53000 -        0x10cae3cb7  dyld (733.8) <EBC07CB6-870A-3A8E-B48A-67F62EA161F3> /usr/lib/dyld
    0x7fff30b39000 -     0x7fff30fb9fe7  com.apple.CoreFoundation (6.9 - 1674.114) <5810CC45-FB5D-3A78-861F-7BE03F9B2FDD> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff64a2b000 -     0x7fff64a2dff7  libDiagnosticMessagesClient.dylib (112) <45E85899-039F-3B99-8789-F497DD9916C2> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff64ef3000 -     0x7fff64ef4ff3  libSystem.B.dylib (1281) <A2C26908-8802-3CA7-8B74-ED4A74AA152C> /usr/lib/libSystem.B.dylib
    0x7fff651d9000 -     0x7fff6522cff7  libc++.1.dylib (800.7) <1D0CB627-8A78-329F-A679-1B5248FF4C59> /usr/lib/libc++.1.dylib
    0x7fff6522d000 -     0x7fff65241fff  libc++abi.dylib (800.7) <7AF668FB-901D-3F45-BA0D-710A235A8D1F> /usr/lib/libc++abi.dylib
    0x7fff65ca5000 -     0x7fff65ca7fff  libfakelink.dylib (149) <7296A5B3-EE44-34E6-810A-2A12C2D3EF68> /usr/lib/libfakelink.dylib
    0x7fff65db7000 -     0x7fff6600fff7  libicucore.A.dylib (64252.0.1) <0F9294A7-6EC0-3279-BF92-3233C89DFA0A> /usr/lib/libicucore.A.dylib
    0x7fff66d48000 -     0x7fff66d79fc6  libobjc.A.dylib (781.2) <7B72F50A-5381-36D7-A616-65D3EA9748A5> /usr/lib/libobjc.A.dylib
    0x7fff67424000 -     0x7fff67436ffb  libz.1.dylib (76) <52250917-039C-3B46-8011-497FEACF3550> /usr/lib/libz.1.dylib
    0x7fff67e9a000 -     0x7fff67e9fff3  libcache.dylib (83) <11C19883-6F99-390D-AF2A-A85A99DDFC48> /usr/lib/system/libcache.dylib
    0x7fff67ea0000 -     0x7fff67eabfff  libcommonCrypto.dylib (60165) <FEE99884-61F0-3332-852B-B0BB8EFF2288> /usr/lib/system/libcommonCrypto.dylib
    0x7fff67eac000 -     0x7fff67eb3fff  libcompiler_rt.dylib (101.2) <D7367E6D-A27D-3209-A3DB-A6F44582E502> /usr/lib/system/libcompiler_rt.dylib
    0x7fff67eb4000 -     0x7fff67ebdfff  libcopyfile.dylib (166.40.1) <91670D15-CB30-3277-8AA9-9A299CEAAE27> /usr/lib/system/libcopyfile.dylib
    0x7fff67ebe000 -     0x7fff67f55fdb  libcorecrypto.dylib (866.80.2) <3B110D82-B403-31E8-8109-8BBC79C928CE> /usr/lib/system/libcorecrypto.dylib
    0x7fff6806c000 -     0x7fff680adff0  libdispatch.dylib (1173.60.1) <5EF42E98-AD0D-3FAE-ABD4-46D791B8343F> /usr/lib/system/libdispatch.dylib
    0x7fff680ae000 -     0x7fff680e3ff7  libdyld.dylib (733.8) <8B0DFE8A-42CF-32C8-B121-83C22BF25F69> /usr/lib/system/libdyld.dylib
    0x7fff680e4000 -     0x7fff680e4ffb  libkeymgr.dylib (30) <7DADC026-70A8-390F-95AF-F3F345760F24> /usr/lib/system/libkeymgr.dylib
    0x7fff680f2000 -     0x7fff680f2ff7  liblaunch.dylib (1738.80.8) <C4EA8803-E506-3514-9839-9BBECC819953> /usr/lib/system/liblaunch.dylib
    0x7fff680f3000 -     0x7fff680f8ff7  libmacho.dylib (949.0.1) <395ABE7C-D2B1-343D-A451-9CEA98FDC12E> /usr/lib/system/libmacho.dylib
    0x7fff680f9000 -     0x7fff680fbff7  libquarantine.dylib (110.40.3) <560961FC-1FEF-3F07-8406-17A36558870E> /usr/lib/system/libquarantine.dylib
    0x7fff680fc000 -     0x7fff680fdff7  libremovefile.dylib (48) <E99833DE-CB1D-31AB-A948-2739AF503599> /usr/lib/system/libremovefile.dylib
    0x7fff680fe000 -     0x7fff68115fff  libsystem_asl.dylib (377.60.2) <21A259BC-F892-34EB-9A67-11232AD8913A> /usr/lib/system/libsystem_asl.dylib
    0x7fff68116000 -     0x7fff68116fff  libsystem_blocks.dylib (74) <8B23F806-8153-3163-B5D8-2C3327E211D8> /usr/lib/system/libsystem_blocks.dylib
    0x7fff68117000 -     0x7fff6819eff7  libsystem_c.dylib (1353.60.8) <99202CC3-2E27-3680-A8FF-5C516C485E90> /usr/lib/system/libsystem_c.dylib
    0x7fff6819f000 -     0x7fff681a2ffb  libsystem_configuration.dylib (1061.80.3) <8A149700-51AA-3205-A9D4-FF2A7BFC5412> /usr/lib/system/libsystem_configuration.dylib
    0x7fff681a3000 -     0x7fff681a6ff7  libsystem_coreservices.dylib (114) <CCC076FA-310D-3FC9-950D-41E0F8DDA5D2> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff681a7000 -     0x7fff681affff  libsystem_darwin.dylib (1353.60.8) <31ACD3CC-6DD9-3F2E-B163-9342BE1D0AB0> /usr/lib/system/libsystem_darwin.dylib
    0x7fff681b0000 -     0x7fff681b7ffb  libsystem_dnssd.dylib (1096.60.2) <BEBB815A-065A-365E-9701-8E05A8CF2040> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff681b8000 -     0x7fff681b9ffb  libsystem_featureflags.dylib (17) <340AD606-7C39-3E6A-BAC3-EA1273FC27A4> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff681ba000 -     0x7fff68207fff  libsystem_info.dylib (538) <B0EBAE05-01AD-3D8E-92CC-5704394FF94A> /usr/lib/system/libsystem_info.dylib
    0x7fff68208000 -     0x7fff68234ff7  libsystem_kernel.dylib (6153.81.5) <23909F45-79C3-34C9-A28F-337915925E5E> /usr/lib/system/libsystem_kernel.dylib
    0x7fff68235000 -     0x7fff6827cfcf  libsystem_m.dylib (3178) <7D775039-51B8-356E-82D7-98449065518A> /usr/lib/system/libsystem_m.dylib
    0x7fff6827d000 -     0x7fff682a4fff  libsystem_malloc.dylib (283.60.1) <00190446-C6A8-3EA6-92D1-850EA85C84CE> /usr/lib/system/libsystem_malloc.dylib
    0x7fff682a5000 -     0x7fff682b2ffb  libsystem_networkextension.dylib (1095.60.2) <1E7A59D0-BBCD-3CB0-8AD1-D442A1A5268E> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff682b3000 -     0x7fff682bcff3  libsystem_notify.dylib (241) <AB3FAC47-A830-3158-8D99-DBC728CED1D6> /usr/lib/system/libsystem_notify.dylib
    0x7fff682bd000 -     0x7fff682c6fef  libsystem_platform.dylib (220) <3DAFCC01-B768-3FFC-AC59-47AAE86BBEA1> /usr/lib/system/libsystem_platform.dylib
    0x7fff682c7000 -     0x7fff682d1fff  libsystem_pthread.dylib (416.60.2) <AAF506F4-9455-3CC4-8E0B-6791E3C0993C> /usr/lib/system/libsystem_pthread.dylib
    0x7fff682d2000 -     0x7fff682d6fff  libsystem_sandbox.dylib (1217.80.1) <C8F3841A-9364-3414-9E3F-9DE3D5FECF0C> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff682d7000 -     0x7fff682d9fff  libsystem_secinit.dylib (62.80.1) <32F36517-9A1C-3D30-85C8-611A2F5E2355> /usr/lib/system/libsystem_secinit.dylib
    0x7fff682da000 -     0x7fff682e1ffb  libsystem_symptoms.dylib (1238.60.1) <2EDF9CE8-4091-30A8-B125-0F25E579694A> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff682e2000 -     0x7fff682f8ff2  libsystem_trace.dylib (1147.80.3) <AE11B1AC-352A-37F0-BCA9-055609070104> /usr/lib/system/libsystem_trace.dylib
    0x7fff682fa000 -     0x7fff682ffffb  libunwind.dylib (35.4) <E867ACDE-EADE-3C91-A2A4-0C401788FD47> /usr/lib/system/libunwind.dylib
    0x7fff68300000 -     0x7fff68335ffe  libxpc.dylib (1738.80.8) <51E3E807-9133-3605-BB5F-D59ED6404ABF> /usr/lib/system/libxpc.dylib
```

**Comment by abylikhsanov** [comment]
How about C++?

**Comment by DavidMansolino** [comment]
> How about C++? I can debug but I am not sure that it will be worth to do as you might already know where it crashes

For me the C++ works fine, it is very strange that it is not working for you. Which version of Webots are you using?

**Comment by abylikhsanov** [comment]
The same. Actually, when I used Proto file instead of the text editor, it worked

**Comment by DavidMansolino** [comment]
I am sorry but I don't understand what you mean by 'using PROTO file' ?

**Comment by dfremont** [comment]
I'm getting essentially the same crash with R2022a and Python 3.8 or 3.9 (3.7 works fine). A Python supervisor with the one line `from controller import Supervisor` is enough to trigger the problem. Here's the backtrace with Python 3.8:

```
Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [14152]

VM Regions Near 0x8:
--> 
    __TEXT                      104477000-10447b000    [   16K] r-x/r-x SM=COW  /usr/local/Cellar/python@3.8/3.8.13/Frameworks/Python.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   org.python.python             	0x0000000104bb08e1 PyTuple_New + 241
1   org.python.python             	0x0000000104bb3559 PyType_Ready + 233
2   org.python.python             	0x0000000104bb3515 PyType_Ready + 165
3   _controller.so                	0x0000000104a2a34f SwigPyPacked_TypeOnce() + 143
4   _controller.so                	0x00000001049c7e0f SwigPyPacked_type() + 47
5   _controller.so                	0x00000001049c5e92 PyInit__controller + 34
6   org.python.python             	0x000000010455b432 _PyImport_LoadDynamicModuleWithSpec + 632
7   org.python.python             	0x000000010455adb5 _imp_create_dynamic + 291
8   org.python.python             	0x00000001044ce7f1 cfunction_vectorcall_FASTCALL + 169
9   org.python.python             	0x00000001044a0333 PyVectorcall_Call + 108
10  org.python.python             	0x000000010453daeb _PyEval_EvalFrameDefault + 28754
11  org.python.python             	0x0000000104540d09 _PyEval_EvalCodeWithName + 1952
12  org.python.python             	0x00000001044a0a51 _PyFunction_Vectorcall + 227
13  org.python.python             	0x00000001045401e6 call_function + 346
14  org.python.python             	0x000000010453d5c9 _PyEval_EvalFrameDefault + 27440
15  org.python.python             	0x00000001044a08ec function_code_fastcall + 106
16  org.python.python             	0x00000001045401e6 call_function + 346
17  org.python.python             	0x000000010453d5a9 _PyEval_EvalFrameDefault + 27408
18  org.python.python             	0x00000001044a08ec function_code_fastcall + 106
19  org.python.python             	0x00000001045401e6 call_function + 346
20  org.python.python             	0x000000010453d671 _PyEval_EvalFrameDefault + 27608
21  org.python.python             	0x00000001044a08ec function_code_fastcall + 106
22  org.python.python             	0x00000001045401e6 call_function + 346
23  org.python.python             	0x000000010453d671 _PyEval_EvalFrameDefault + 27608
24  org.python.python             	0x00000001044a08ec function_code_fastcall + 106
25  org.python.python             	0x00000001045401e6 call_function + 346
26  org.python.python             	0x000000010453d671 _PyEval_EvalFrameDefault + 27608
27  org.python.python             	0x00000001044a08ec function_code_fastcall + 106
28  org.python.python             	0x00000001044a1d37 object_vacall + 277
29  org.python.python             	0x00000001044a1e78 _PyObject_CallMethodIdObjArgs + 217
30  org.python.python             	0x0000000104559ef9 PyImport_ImportModuleLevelObject + 1564
31  org.python.python             	0x000000010453bc95 _PyEval_EvalFrameDefault + 20988
32  org.python.python             	0x0000000104540d09 _PyEval_EvalCodeWithName + 1952
33  org.python.python             	0x00000001045369f6 PyEval_EvalCode + 51
34  org.python.python             	0x00000001045342b6 builtin_exec + 592
35  org.python.python             	0x00000001044ce7f1 cfunction_vectorcall_FASTCALL + 169
36  org.python.python             	0x00000001044a0333 PyVectorcall_Call + 108
37  org.python.python             	0x000000010453daeb _PyEval_EvalFrameDefault + 28754
38  org.python.python             	0x0000000104540d09 _PyEval_EvalCodeWithName + 1952
39  org.python.python             	0x00000001044a0a51 _PyFunction_Vectorcall + 227
40  org.python.python             	0x00000001045401e6 call_function + 346
41  org.python.python             	0x000000010453d5c9 _PyEval_EvalFrameDefault + 27440
42  org.python.python             	0x00000001044a08ec function_code_fastcall + 106
43  org.python.python             	0x00000001045401e6 call_function + 346
44  org.python.python             	0x000000010453d5a9 _PyEval_EvalFrameDefault + 27408
45  org.python.python             	0x00000001044a08ec function_code_fastcall + 106
46  org.python.python             	0x00000001045401e6 call_function + 346
47  org.python.python             	0x000000010453d671 _PyEval_EvalFrameDefault + 27608
48  org.python.python             	0x00000001044a08ec function_code_fastcall + 106
49  org.python.python             	0x00000001045401e6 call_function + 346
50  org.python.python             	0x000000010453d671 _PyEval_EvalFrameDefault + 27608
51  org.python.python             	0x00000001044a08ec function_code_fastcall + 106
52  org.python.python             	0x00000001044a1d37 object_vacall + 277
53  org.python.python             	0x00000001044a1e78 _PyObject_CallMethodIdObjArgs + 217
54  org.python.python             	0x0000000104559ef9 PyImport_ImportModuleLevelObject + 1564
55  org.python.python             	0x000000010453bc95 _PyEval_EvalFrameDefault + 20988
56  org.python.python             	0x0000000104540d09 _PyEval_EvalCodeWithName + 1952
57  org.python.python             	0x00000001045369f6 PyEval_EvalCode + 51
58  org.python.python             	0x000000010456ec24 run_eval_code_obj + 102
59  org.python.python             	0x000000010456dea0 run_mod + 82
60  org.python.python             	0x000000010456dfcd pyrun_file + 133
61  org.python.python             	0x000000010456c785 PyRun_SimpleFileExFlags + 655
62  org.python.python             	0x0000000104583ed1 Py_RunMain + 1891
63  org.python.python             	0x0000000104584218 pymain_main + 306
64  org.python.python             	0x0000000104584266 Py_BytesMain + 42
65  libdyld.dylib                 	0x00007fff204daf3d start + 1```

**Comment by BenjaminDeleze** [comment]
Hi,
What is your MacOS version?
Are you using Python from Homebrew or Python.org?

**Comment by dfremont** [comment]
I'm using macOS 11.6.2. The log I posted above was with Python 3.8 installed through Homebrew, but I've gotten a similar crash with Python 3.9 installed from Python.org. I've seen the crash both when running Webots inside and outside of a virtual environment (in all cases with the "Python command" option left as the default "python").

**Comment by dfremont** [comment]
Is there any other information I can provide to help fix this? We're OK using Python 3.7 if we have to for the moment, but it would be nice to be able to use newer Python versions.

**Comment by omichel** [comment]
I believe this problem is fixed in the new version we are preparing. Can you test the R2022b [nightly build](https://github.com/cyberbotics/webots/releases) and confirm the issue is gone? I tested with Python 3.7, 3.8, 3.9 and 3.10 (from python.org) on the latest version of macOS 11 and everything works as expected. I am closing the issue for now. Feel free to re-open if needed.

**Comment by dfremont** [comment]
In the mean time I upgraded to macOS 12.3.1, and it's still crashing for me with Python 3.9 (from python.org):

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Codes:       0x0000000000000001, 0x0000000000000010
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [34540]

VM Region Info: 0x10 is not in any region.  Bytes before following region: 4301877232
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      100697000-100917000    [ 2560K] r-x/r-x SM=COW  ...R/*/python3.9

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   Python                        	       0x1017c78d0 _PyObject_GC_Alloc + 48
1   Python                        	       0x1017c7a65 _PyObject_GC_New + 21
2   Python                        	       0x1016b7053 PyDict_New + 67
3   _controller.so                	       0x1011af60f SWIG_Python_TypeCache() + 47
4   _controller.so                	       0x1011ad965 PyInit__controller + 21
5   python3.9                     	       0x1007f60f8 _PyImport_LoadDynamicModuleWithSpec + 632
6   python3.9                     	       0x1007f5994 _imp_create_dynamic + 308
7   python3.9                     	       0x100722337 cfunction_vectorcall_FASTCALL + 215
8   python3.9                     	       0x1007c7a29 _PyEval_EvalFrameDefault + 28153
9   python3.9                     	       0x1007cb763 _PyEval_EvalCode + 3091
10  python3.9                     	       0x1006e0420 _PyFunction_Vectorcall + 256
11  python3.9                     	       0x1007ca7ab call_function + 411
12  python3.9                     	       0x1007c760e _PyEval_EvalFrameDefault + 27102
13  python3.9                     	       0x1006e0515 function_code_fastcall + 229
14  python3.9                     	       0x1007ca7ab call_function + 411
15  python3.9                     	       0x1007c75f1 _PyEval_EvalFrameDefault + 27073
16  python3.9                     	       0x1006e0515 function_code_fastcall + 229
17  python3.9                     	       0x1007ca7ab call_function + 411
18  python3.9                     	       0x1007c76ad _PyEval_EvalFrameDefault + 27261
19  python3.9                     	       0x1006e0515 function_code_fastcall + 229
20  python3.9                     	       0x1007ca7ab call_function + 411
21  python3.9                     	       0x1007c76ad _PyEval_EvalFrameDefault + 27261
22  python3.9                     	       0x1006e0515 function_code_fastcall + 229
23  python3.9                     	       0x1007ca7ab call_function + 411
24  python3.9                     	       0x1007c76ad _PyEval_EvalFrameDefault + 27261
25  python3.9                     	       0x1006e0515 function_code_fastcall + 229
26  python3.9                     	       0x1006e1927 object_vacall + 471
27  python3.9                     	       0x1006e1b86 _PyObject_CallMethodIdObjArgs + 246
28  python3.9                     	       0x1007f4826 PyImport_ImportModuleLevelObject + 1350
29  python3.9                     	       0x1007c5f03 _PyEval_EvalFrameDefault + 21203
30  python3.9                     	       0x1007cb763 _PyEval_EvalCode + 3091
31  python3.9                     	       0x1007c0b60 PyEval_EvalCode + 64
32  python3.9                     	       0x1007bd9ba builtin_exec + 618
33  python3.9                     	       0x100722337 cfunction_vectorcall_FASTCALL + 215
34  python3.9                     	       0x1007c7a29 _PyEval_EvalFrameDefault + 28153
35  python3.9                     	       0x1007cb763 _PyEval_EvalCode + 3091
36  python3.9                     	       0x1006e0420 _PyFunction_Vectorcall + 256
37  python3.9                     	       0x1007ca7ab call_function + 411
38  python3.9                     	       0x1007c760e _PyEval_EvalFrameDefault + 27102
39  python3.9                     	       0x1006e0515 function_code_fastcall + 229
40  python3.9                     	       0x1007ca7ab call_function + 411
41  python3.9                     	       0x1007c75f1 _PyEval_EvalFrameDefault + 27073
42  python3.9                     	       0x1006e0515 function_code_fastcall + 229
43  python3.9                     	       0x1007ca7ab call_function + 411
44  python3.9                     	       0x1007c76ad _PyEval_EvalFrameDefault + 27261
45  python3.9                     	       0x1006e0515 function_code_fastcall + 229
46  python3.9                     	       0x1007ca7ab call_function + 411
47  python3.9                     	       0x1007c76ad _PyEval_EvalFrameDefault + 27261
48  python3.9                     	       0x1006e0515 function_code_fastcall + 229
49  python3.9                     	       0x1006e1927 object_vacall + 471
50  python3.9                     	       0x1006e1b86 _PyObject_CallMethodIdObjArgs + 246
51  python3.9                     	       0x1007f4826 PyImport_ImportModuleLevelObject + 1350
52  python3.9                     	       0x1007c5f03 _PyEval_EvalFrameDefault + 21203
53  python3.9                     	       0x1007cb763 _PyEval_EvalCode + 3091
54  python3.9                     	       0x1007c0b60 PyEval_EvalCode + 64
55  python3.9                     	       0x10081125d pyrun_file + 333
56  python3.9                     	       0x10080f32e PyRun_SimpleFileExFlags + 734
57  python3.9                     	       0x10082e7e3 Py_RunMain + 2067
58  python3.9                     	       0x10082ed13 pymain_main + 403
59  python3.9                     	       0x10082ed6b Py_BytesMain + 43
60  dyld                          	       0x10799251e start + 462```

**Comment by dfremont** [comment]
(To be clear, that crash log is with the nightly version you suggested.)

**Comment by omichel** [comment]
I tested again and it worked out for all these Pythons version from python.org:

- python 3.7.9
- python 3.8.10
- python 3.9.13
- python 3.10.5

Can you check that you have exactly the same versions, including the revision number?

**Comment by dfremont** [comment]
I installed 3.9.13 from python.org and that worked! It turns out I was wrong in my last post above: the crash was with Python installed through `pyenv`, not from python.org. I installed 3.9.13 with `pyenv` and got the same crash, so I guess the issue is with `pyenv`. Does Webots not support Python being installed that way?

**Comment by omichel** [comment]
OK, this reassuring. Webots only supports out-of-the-box the official Python from https://python.org and also the one from homebrew. However, you can recompile the wrapper for your own flavor of Python as explained here: https://www.cyberbotics.com/doc/guide/using-python#use-an-alternative-python-version

I am closing (again) this issue as I believe it is finally resolved.
